### ISSUE TITLE
can't find syncfusion-ej2-wordprocessor-18.1.0.1.jar

### ISSUE THREAD

**Issue by fuukangun** [SyncfusionExamples/EJ2-DocumentEditor-WebServices#6]
this project don't have syncfusion-ej2-wordprocessor-18.1.0.1.jar，how can we get this .jar file？

**Comment by gunasekarant** [comment]
Hi @fuukangun ,

Please refer the below documentation for more information about downloading syncfusion-ej2-wordprocessor JAR file.
https://ej2.syncfusion.com/documentation/document-editor/web-services/java/#download-jar-file

Please let us know if you have any questions.

Regards
Gunasekaran
